# Bundle name: EzSystemsForumPhp2013DemoBundle
# Controller: ForumPhp
#
# Override (controller is optional):
# location_view:
#     full:
#         <name>:
#             template: <path>
#             match:
#                 <matcher>: <value>
#             controller: Bundle:Controller:action
system:
    forumphp:
        location_view:
            full:
                conference:
                    template: "EzSystemsForumPhp2013DemoBundle:full:conference.html.twig"
                    match:
                        Identifier\ContentType: [conference]
                conferencier:
                    controller: "EzSystemsForumPhp2013DemoBundle:ForumPhp:showSpeaker"
                    template: "EzSystemsForumPhp2013DemoBundle:full:conferencier.html.twig"
                    match:
                        Identifier\ContentType: [conferencier]
                folder:
                    controller: "EzSystemsForumPhp2013DemoBundle:ForumPhp:showSpeakers"
                    template: "EzSystemsForumPhp2013DemoBundle:full:folder.html.twig"
                    match:
                        Identifier\ContentType: [folder]
            line:
                conferencier:
                    template: "EzSystemsForumPhp2013DemoBundle:line:conferencier.html.twig"
                    match:
                        Identifier\ContentType: [conferencier]
