parameters:
#    ez_systems_forum_php2013_demo.example.class: EzSystems\ForumPhp2013DemoBundle\Example

services:
#    ez_systems_forum_php2013_demo.example:
#        class: %ez_systems_forum_php2013_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
